-- Migration to remove user_supplier_credentials table and credential_id from property_suppliers
-- 
-- IMPORTANT: Use the database-specific migration file:
-- - For MySQL: run remove_credentials_migration_mysql.sql
-- - For SQLite: run remove_credentials_migration_sqlite.sql
--
-- These migrations will:
-- 1. Remove the credential_id column from property_suppliers table
-- 2. Drop the user_supplier_credentials table
-- 3. Clean up related foreign keys and indexes

-- This file is kept for reference only
-- DO NOT RUN THIS FILE - use the database-specific versions instead
